### ISSUE TITLE
[Bug] Cannot import name 'get_correct_sampler' from 'modules.processing'

### ISSUE THREAD

**Issue by Miyuutsu** [bbc-mc/sdweb-xyplus#1]
```
Traceback (most recent call last):
  File "/home/miyuu/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/home/miyuu/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/home/miyuu/stable-diffusion-webui/scripts/xy_grid_plus.py", line 65, in <module>
    from modules.processing import process_images, Processed, get_correct_sampler, StableDiffusionProcessingTxt2Img
ImportError: cannot import name 'get_correct_sampler' from 'modules.processing' (/home/miyuu/stable-diffusion-webui/modules/processing.py)
```

This seems to have been removed entirely with commit cdc8020 to the webui.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/compare/828438b..cdc8020#diff-1fe5b15d29310b37af0c4560da365990f4e6eee7b99bf3f041cfa18ebb11610f

**Comment by bbc-mc** [comment]
Thank you for reporting.

I checked script and confirmed this bug.

Also I found there are issues on sampler things (include xy_grid) with webui, and still waiting to merge.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/4910

I'll check xy_grid.py after this merge and will work on it.
